name: 'Terraform - Docs'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - '.github/workflows/*.yml'
#  schedule:
#      - cron: '49 5 * * 0' # runs every sunday at 5:49 am (UTC)

permissions: write-all

jobs:
  terraform-docs:
    name: 'Terraform Docs'
    strategy:
      matrix:
        ## runs-on: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
##      with:
##        ref: ${{ github.event.pull_request.head.ref }}
##        repository: ${{ github.event.pull_request.head.repo.full_name }}

    ## Install Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false
        terraform_version: latest
              
    ## Show Terraform version
    - name: Show Terraform Version
      run: terraform version

    ## Terraform Check Format
    - name: Check Terraform Format
      run: terraform fmt
    ## if there are errors, then Action fails

#    - name: Generate tfvars
#      uses: terraform-docs/gh-actions@main
#      run: terraform-docs tfvars json terraform.tfvars

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        config-file: .terraform-docs.yml
        working-dir: .
        git-push: "true"

