name: Terraform - Lint
on:
  [workflow_dispatch]

  #push:
  #  branches: [ main ]
  #pull_request:

permissions: read-all

jobs:
  tflint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] ## [,macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      name: Checkout source code

    - uses: actions/cache@v4
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        tflint_version: latest #v0.52.0
    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init
      env:
        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run TFLint
      id: tflint
      run: |
        echo "Running TFLint..."
        OUTPUT=$(tflint -f compact || true)

        echo "$OUTPUT"

        while IFS= read -r line; do
          # Format of compact output: PATH:LINE:COLUMN: MESSAGE
          FILE=$(echo "$line" | cut -d: -f1)
          LINE=$(echo "$line" | cut -d: -f2)
          MESSAGE=$(echo "$line" | cut -d: -f4-)

          echo "::error file=$FILE,line=$LINE::TFLint: $MESSAGE"
        done <<< "$OUTPUT"
